on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.bioc-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2022, bioc-version: 'devel', bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor'}
        - { os: macOS-13,     bioc-version: 'devel', bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor'}
        - { os: macOS-14,     bioc-version: 'devel', bioc-mirror: 'https://ftp.gwdg.de/pub/misc/bioconductor'}
        - { os: ubuntu-22.04, bioc-version: 'devel', bioc-mirror: 'https://packagemanager.posit.co/bioconductor'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
          
      - uses: actions/checkout@v4
          
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: ${{ matrix.config.bioc-mirror }}
          
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install TinyTex
        uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_INSTALLER: TinyTeX

      - name: Install latex fonts
        if: runner.os != 'Windows'
        run: |
          tlmgr update --self && tlmgr install courier makeindex bera nowidow parnotes marginfix
        shell: bash

      - name: Install latex fonts
        if: runner.os == 'Windows'
        run: |
          tlmgr update --self && tlmgr install courier makeindex bera nowidow parnotes marginfix
        shell: pwsh
        
      - name: Install dependencies (non-Windows)
        uses: r-lib/actions/setup-r-dependencies@v2
          
      - name: Bioc - Build, Install, Check
        uses: grimbough/bioc-actions/build-install-check@v1

      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help' 

